config/routes.rb
BettrLink::Application.routes.draw do

  #####################################
  # API
  #####################################

  # http://andrewberls.com/blog/post/api-versioning-with-rails-4
  # http://railscasts.com/episodes/350-rest-api-versioning

  constraints subdomain: 'api' do
    scope module: 'api', defaults: { format: :json } do
      namespace :v1, as: :api, constraints: Constraints::Api.new(version: 1, default: true) do
        get '/analyze', to: 'links#analyze', as: :analyze
      end
    end
  end

  #####################################
  # Site
  #####################################

  resources :users, :links, :tags

  # match '/login' => 'users#login', via: [:get, :post], as: :login
  post '/login' => 'users#login', as: :login
  get '/logout' => 'users#logout', as: :logout

  get '/:user_name/dashboard' => 'site#dashboard', as: :dashboard
  get '/:user_name/settings' => 'site#settings', as: :settings

  get '/parse' => 'links#parse', as: :parse

  root 'site#home', as: :site_path

end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  before_filter :require_user, except: :home

  def home
  end

  def dashboard
  end

  def settings
  end


end

app/helpers/site_helper.rb
module SiteHelper
end

app/views/site/dashboard.html.erb
<h1>Dashboard</h1>

<%= current_user.inspect %>
<%= link_to 'add link', new_link_path %>

app/views/site/home.html.erb
<h3> Sign Up </h3>
<div class='signup'>
  <%= button_form_for :user, url: '/users' do |f| %>
    <div class="field-container">
      <%= f.text_field :name, class: 'signup' %>
      <%= f.label :name %>
      <span id='fs-name' class='field-standin'></span>
    </div>
    <div class="field-container">
      <%= f.text_field :email, class: 'signup' %>
      <%= f.label :email %>
      <span id='fs-email' class='field-standin'></span>
    </div>
    <div class="field-container">
      <%= f.password_field :password, class: 'signup' %>
      <%= f.label :password %>
      <span id='fs-password' class='field-standin'></span>

    </div>
    <div class="field-container">
      <%= f.password_field :password_confirmation, class: 'signup' %>
      <%= f.label :confirm_password %>
      <span id='fs-password-confirmation' class='field-standin'></span>

    </div>

    <%= f.button "sign up", class: 'button-alt' %>
  <% end %>
</div>